enableSearch = true
[header]
layout = "hybrid"
[article]
showTableOfContents = true
showWordCount = true
[homepage]
layout = "post"
showRecent= true
[list]
showSummary=true
showTableOfContents = true
