# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Systems++"
email: rr.underwood94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Thoughts and ramblings of a student of computer science.
    This site will focus on computer systems design, programming, and tricks I learn along the way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robertu94.github.io" # the base hostname & protocol for your site
github_username:  robertu94

author: Robert Underwood
header_pages:
    - about.md
    - learning.md
    - presentations.md
    - guides.md

collections:
  learning:
    output: true
    permalink: /learning/:title
  presentations:
    output: true
    permalink: /presentations/:title
  guides:
    output: true
    permalink: /guides/:title

# Build settings
markdown: kramdown
theme: minima
google_analytics: UA-146577621-1
